/**
 * This file contains helper utilities.
 * DO NOT EDIT THIS FILE.
 */
#ifndef MOVIEREVIEW_UTILS_H
#define MOVIEREVIEW_UTILS_H
#include "Entries.h"
#include <string>
#include <vector>

using namespace std;

void flush();

vector<string> split(string s);

Entries read_input_file(string filename);

#endif //MOVIEREVIEW_UTILS_H
