/**
 * This is a lightly edited version of code taken from
 * Manley, E.D., & Urness, T. M.,
 * http://nifty.stanford.edu/2016/manley-urness-movie-review-sentiment/CS2SentimentStarterCode.zip,
 * last access Sep 15, 2016.
 *
 * NOTE: DO NOT EDIT THIS FILE!
 */

#ifndef WORDENTRY_H
#define WORDENTRY_H

#include <string>
#include <iostream>

using namespace std;

class WordEntry {

//    private:
        /**
         * The word (or punctuation).
         */
        string word;

        /**
         * The total number of times the word appeared
         * in the tagged movie review file.
         */
        int num_appearances;

        /**
         * The (sum) total score for the word.
         */
        int total_score;

    public:
        WordEntry();
        WordEntry(string the_word, int the_score);
        void add_new_appearance(int score);
        string get_word() const;
        int get_num_appearances() const;
        double get_average() const;


    friend ostream& operator<<(ostream& ostr, const WordEntry& entry);
};

ostream& operator<<(ostream& ostr, const WordEntry& entry);

#endif
